[package]
name = "server"
version = "0.1.0"
authors = ["Danny Meyer <danny@xasopheno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weresocool_error = { path = "../audio/error" } 
weresocool = { path = "../audio" } 
actix-cors = "0.2.0"
actix-files = "0.2.1"
actix-web = "2.0.0"
actix-service = "1.0.5"
async-std = "1.5.0"
actix-http = "1.0.1"
actix-rt = "1.0.0"
env_logger = "0.7.1"
serde = "1.0.105"
rust-embed = "5.5.1"
mime_guess = "2.0.3"
